"""LoRA-B training recipe: Q + passages → reasoned A (RAFT-style).

This is the experimental condition - trained to reason over passages.
Uses synthetic targets generated by Claude Haiku.
"""

from pathlib import Path
from typing import Any


def train_lora_b(
    train_data: list[dict[str, Any]],
    corpus: dict[str, dict],
    output_dir: Path,
    config_path: Path,
    seed: int = 42,
    offline: bool = False,
) -> None:
    """Train LoRA-B adapter.

    Args:
        train_data: Training examples with "synthetic_target" field
        corpus: Full corpus for distractor sampling
        output_dir: Directory to save adapter
        config_path: Path to lora_b.yaml config
        seed: Random seed
        offline: If True, skip W&B logging and HF Hub push

    Note:
        Uses SAME distractor sampling as LoRA-A' for clean ablation.
        The only difference is the target format (reasoned vs. answer-only).
    """
    raise NotImplementedError("TODO: Implement in M6")


def prepare_lora_b_dataset(
    examples: list[dict],
    corpus: dict[str, dict],
    seed: int = 42,
) -> Any:
    """Prepare dataset for LoRA-B training.

    Formats examples as (input, target) pairs where:
    - input: question + 5 passages (same as LoRA-A')
    - target: "Based on... [reasoning with citations]... Answer: [label]"
    """
    raise NotImplementedError("TODO: Implement in M6")


def run_smoke_test(config_path: Path) -> bool:
    """Run 1-step smoke test on CPU."""
    raise NotImplementedError("TODO: Implement in M6")
